config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :carts
  resources :books
  resources :charges
  devise_for :users
  get "search", to: "books#search"
  get "recent_book", to: "books#recent_book"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "books#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
 <div class="container">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%= link_to root_path do %>
      <%= image_tag "icon.png", class: "navbar-brand core-sprite hide-text" %>
    <% end %>
    <%= link_to "Books", recent_book_path %>
    <a class="nav-link explore-icon hide-text" href="#">Bundles</a>
    <form class="form-inline my-2 my-lg-0 " action="<%= search_path %>">
      <input class="form-control mr-sm-2 search" type="Text" placeholder="Search Leanpub" aria-label="Search" name="search_key" >
      <%= button_to "", search_path, class: "btn btn-default" %>
     </form>
      <% if session[:cart_id] == nil %>
      <%= link_to "<i class='fa fa-shopping-cart'></i>".html_safe, carts_path %>
      <% else %>
        <%= link_to "<i class='fa fa-shopping-cart'></i>".html_safe, cart_path(session[:cart_id]) %>
      <% end %>
      <div class="dropdown">
        <button class="dropbtn">&#9776</button>
        <div class="dropdown-content">
          <% if user_signed_in? %>
            <%= link_to "Create Book", new_book_path %>
            <br>
            <%= current_user.email %>
            <br>
            <%= link_to "Email-settings", edit_user_registration_path(current_user), class: "nav-item profile-icon hide-text" %>
            <%= link_to "logout", destroy_user_session_path, method: :delete, class: "no-text-decoration" %>
          <% else %>
            <%= link_to "sign in", new_user_session_path %>
            <%= link_to "sign up", new_user_registration_path %>
          <% end %>
          <a class="nav-item  wishlist-icon" href="#">wishlist</a>
        </div>
      </div>
     </div>
  </div>
</nav>

app/views/shared/_search.html.erb
<!--  <div class="container">
  <div class= "a">
    <div class="categories_title">
      <u>BOOKS</u>
    </div>
    <div class="free_books">
      <div class="book_info">
        <% @books.each do |book| %>
          <div class="book_image">
            <div class="image_source">
              <%= image_tag("ruby.jpg") %>
            </div>
          </div>
          <div class="book_details">
            <div class="title_n_option">
              <div class="title">
                <%= book.title %>
              </div>
              <div class="options">
                <%= link_to "Show", book, class: "btn btn-outline-dark" %>
              </div>
            </div>
            <div class="book_author">
              <%= book.user.name %>
            </div>
            <div class="about">
              <%= book.about %>
            </div>
            <br>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  </div> -->
  <div class="container">
    <div class="search-page">
    <br>
    <h1> Books</h1>
    <% @books.each do |book| %>
    <div class= "cover-detail">
      <div class="cover-image">
        <%= image_tag book.coverimage %>
      </div>
      <div class="book-detail">
        <div class="book-title">
            <%= link_to book.title, book %>
        </div>
        <div class="book-author">
          <%= book.user.name %>
        </div>
        <div class="about-book">
            <%= book.about.truncate(400) %>
        </div>
      </div>
    </div>
    <% if current_user == book.user %>
    <% link_to "Destroy", book, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
    <% end %>
    <% end %>
    </div>
  </div>