config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :carts
  resources :books
  resources :charges
  devise_for :users
  get "search", to: "books#search"
  get "recent_book", to: "books#recent_book"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "books#index"
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :line_items, dependent: :destroy
  # mount_uploader :coverimage, PhotoUploader
  has_one_attached :coverimage
  has_one_attached :pdf_file
  before_destroy :ensure_not_referenced_by_any_line_item
  validates :title, presence: true

  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line Items present")
      throw :abort
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  def search
    if params[:search_key]
      @books = Book.where("title LIKE ?",
                          "%#{params[:search_key]}%")
    end
  end

  def recent_book
    @books = Book.all.order("created_at DESC")
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.user = current_user
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :author_price, :selling_price, :book_index, :about, :book_category, :youtube_link, :retired, :published, :user_id, :cover, :pdf_file, :coverimage)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<!-- <%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :author_price %>
    <%= form.text_field :author_price %>
  </div>
  <div class="field">
    <%= form.label :selling_price %>
    <%= form.text_field :selling_price %>
  </div>
  <div class="field">
    <%= form.label :selling_price %>
    <%= form.text_field :selling_price %>
  </div>
  <div class="field">
    <%= form.label :book_index %>
    <%= form.text_area :book_index %>
  </div>
  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about, rows: 10, cols: 60 %>
  </div>
  <div class="field">
    <%= form.label :book_category %>
    <%= form.text_field :book_category %>
  </div>
  <div class="field">
    <%= form.label :youtube_link %>
    <%= form.url_field :youtube_link %>
  </div>
  <div class="field">
    <%= form.label :retired %>
    <%= form.check_box :retired %>
  </div>
  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published %>
  </div>
  <div class="field">
    <%= form.label :user_id %>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %> -->
<div class="container">
<%= form_with(model: book, class: "form-group", local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title, class: "label" %>
    <%= form.text_field :title, required: true, class: "form-control" %>
  </div>
  <div class="field">
    <%= form.label "Author Price", class: "label" %>
    <%= form.text_field :author_price, class: "form-control" %>
  </div>
   <div class="field">
    <%= form.label :selling_price, class: "label" %>
    <%= form.text_field :selling_price, class: "form-control" %>
  </div>
  <div class="field">
    <%= form.label :book_index, class: "label" %>
    <%= form.text_area :book_index, class: "form-control" %>
  </div>
  <div class="field">
    <%= form.label "Cover image", class: "label" %>
    <%= form.file_field :coverimage, class: "form-control" %>
  </div>
  <div class="field">
    <%= form.label :about, class: "label" %>
    <%= form.text_area :about, rows: 10, cols: 60, class: "form-control" %>
  </div>
  <div class="field">
    <br>
    <%= form.label :book_category, class: "label" %>
    <% form.text_field :book_category, class: "form-control" %>
    <%= form.select :book_category, ["Biography", "Technology", "Science", "Fiction"], class: "form-control" %>
  </div>
  <div class="field">
    <%= form.label "upload book", class: "label" %>
    <%= form.file_field :pdf_file, class: "form-control" %>
  </div>
  <div class="field">
    <%= form.label :youtube_link, class: "label" %>
    <%= form.url_field :youtube_link, class: "form-control" %>
  </div>
  <div class="field">
    <%= form.label :retired, class: "label" %>
    <%= form.check_box :retired, class: "form-check" %>
  </div>
  <div class="field">
    <%= form.label :published, class: "label" %>
    <%= form.check_box :published, class: "form-check" %>
  </div>
  <div class="field">
    <%= form.hidden_field :user_id, class: "form-control", value: current_user.id %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit "Create Book", class: "btn btn-outline-info btn-block" %>
  </div>
<% end %>
</div>

app/views/books/_view_book.html.erb
<% #= link_to "view", @book.pdf_file %>
<%= session[:cart_id].inspect %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
    
<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<!-- <p id="notice"><%= notice %></p>
<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author price</th>
      <th>Selling price</th>
      <th>Book index</th>
      <th>About</th>
      <th>Book category</th>
      <th>Youtube link</th>
      <th>Retired</th>
      <th>Published</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author_price %></td>
        <td><%= book.selling_price %></td>
        <td><%= book.book_index %></td>
        <td><%= book.about %></td>
        <td><%= book.book_category %></td>
        <td><%= book.youtube_link %></td>
        <td><%= book.retired %></td>
        <td><%= book.published %></td>
        <td><%= book.user.name %></td>
        <td><%= link_to "Show", book %></td>
        <% if current_user == book.user %>
          <td><%= link_to "Edit", edit_book_path(book) %></td>
          <td><%= link_to "Destroy", book, method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>
<% if current_user %>
  <%= link_to "New Book", new_book_path %>
<% else %>
  <%= link_to "New Book", new_user_session_path %>
<% end %>
-->

<%= render "shared/search" %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/recent_book.html.erb
<%= render "shared/search" %>

app/views/books/search.html.erb
<%= render "shared/search"%>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<section class="show-section">
  <div class= "show-container">
    <div class="title">
      <h1 class="book-title"><%= @book.title %></h1>
    </div>
    <br />
    <br />
    <div class="bodies">
      <div class="cover-name">
        <div class="cover-image">
        <%= image_tag @book.coverimage, class: "image" %>
        </div>
        <div class="author-name">
            <%= @book.user.name %>
        </div>
      </div>
      <div class="pricing-ecart">
      <div class="actual_and_suggestion d-flex">
          <div class="minimum-price text-center ">
            <%= @book.selling_price - @book.selling_price * 0.2 %><br>
            <span class="badge min_price">Minimum Price</span>
          </div>
          &nbsp&nbsp&nbsp&nbsp&nbsp
          <div class="suggested-price text-center ">
            <%= @book.selling_price %>
            <br>
            <span class="badge suggest_price">Suggested Price</span>
          </div>
        </div>
      <div class="pricing">
        <h6>YOU PAY: <span id="demo1"></span></h6>
        <div class="rangeslider1"> 
          <input type="range" min=<%=@book.author_price%> max=<%=@book.selling_price * 2 %> value=<%=@book.selling_price %> 
                  class="myslider form-control w-250" id="sliderRange1">  
       </div> 
        <br />
        <p>Author Earns: <span id="demo2"></span></p> 
        <%# <div class="rangeslider2"> 
          <input type="range" min="1" max="100" value="1"
                  class="myslider" id="sliderRange2"> 
          <p>Value: <span id="demo2"></span></p> 
       </div>  %>

      </div>
      <div class="ecart">
        <span><%= button_to "Add to cart", line_items_path(book_id: @book.id), class: "btn btn-primary btn-block" %></span>
      </div> 
      </div>
    </div>
  </div>
</section>
<br />
<section class="about-section">
<div class="about">  
  <h6>About The Book</h6>
  <p>
  <%=render "view_book"%>
  <%= @book.about %>
  </p>
</div>
</section>
<%= link_to "view", @book.pdf_file%>
<!-- <%= link_to "Edit", edit_book_path(@book) %> |
<%= link_to "Back", books_path %> -->
<script> 
  var rangeslider1 = document.getElementById("sliderRange1");
  var rangeslider2 = document.getElementById("sliderRange2"); 
  var output1 = document.getElementById("demo1");
  var output2 = document.getElementById("demo2"); 
  output1.innerHTML = parseInt(rangeslider1.value); 
  output2.innerHTML = parseInt(rangeslider1.value) - parseInt(rangeslider1.value*0.2)
  rangeslider1.oninput = function() { 
    output1.innerHTML = this.value; 
    output2.innerHTML = parseInt(rangeslider1.value) - parseInt(rangeslider1.value*0.2)
    console.log(output1.innerHTML)
  }
  // rangeslider2 = output2.innerHTML
  // rangeslider2.output2.innerHTML
  // rangeslider2.oninput = function() { 
  //   // output1.innerHTML = this.value; 
  //   // output2.innerHTML = parseInt(rangeslider1.value) - parseInt(rangeslider1.value*0.2)
  //   output2.innerHTML
  // } 
  // alert(output2.innerHTML)
</script> 